config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users do
    resources :photos
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
  validates :name, presence: true
  #validates :file, presence: true
  validates :user_id, presence: true
  mount_uploader :file, PhotoUploader
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, presence: true
  validates :phone_number, presence: true
  validates :date_of_birth, presence: true
  validates :last_name, presence: true
  validates :first_name, presence: true

  has_many :photos
  def full_name
    "#{last_name.upcase} #{first_name.capitalize}"
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :load_user
  before_action :load_photo, only: [:show, :edit, :destroy]

  def index
    @user = User.find(params[:user_id])
    @photos = Photo.all.where("user_id": @user).all
    end

  def new
    @photo = Photo.new
    @photo.user_id = @user.id
  end

  def create
    authorized_attributes = params.require(:photo).permit(
        :name,
        :file,
        :user_id,
    )
    @photo = Photo.new authorized_attributes
    if @photo.save
      redirect_to(user_photos_path)
    else
      render 'new'
    end
  end

  def load_user
    @user = User.find params[:user_id]
  end

  def load_photo
    @photo = @user.photos.find(params[:id])
  end

  def update
    authorized_attributes = params.require(:photo).permit(
        :name,
        :file,
        :user_id,
    )
    if @photo.update_attributes authorized_attributes
      redirect_to(user_photo_path)
    else
      render 'edit'
    end
  end

  def destroy
    @photo.destroy
    redirect_to user_photos_path(@user  )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :load_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all.order(:last_name)
  end

  def new
    @user = User.new
  end

  def create
    authorized_attributes = params.require(:user).permit(
        :first_name,
        :last_name,
        :date_of_birth,
        :phone_number,
        :email
    )
    @user = User.new authorized_attributes
    if @user.save
      redirect_to(users_path)
    else
      render 'new'
    end
  end


  def load_user
    @user = User.find(params[:id])
  end

  def update
    authorized_attributes = params.require(:user).permit(
        :first_name,
        :last_name,
        :date_of_birth,
        :phone_number,
        :email
    )
    if @user.update_attributes authorized_attributes
      redirect_to(user_path)
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AnnuaireProject</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<div class="header">
  <h1><i>Annuaire Project Application</i></h1>
</div>
<main>
  <%= yield %>
</main>
</body>
</html>

app/views/photos/_form.html.erb
<div class="row justify-content-center" >
  <%=  form_for @photo, url: [@user, @photo], :html => { :multipart => true }  do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, :class => "form-control" %>
      <% if @photo.errors[:name].present? %>
        <div class="error">
          <%= @photo.errors[:name].to_sentence %>
        </div>
      <% end %>
    </div>
    <div class="form-group">
      <%= f.label :file %>
      <%= f.file_field :file, :class => "form-control"%>
      <% if @photo.errors[:file].present? %>
        <div class="error">
          <%= @photo.errors[:file].to_sentence %>
        </div>
      <% end %>
    </div>
    <div class="form-group">
      <%= f.label :user_id %>
      <%= f.collection_select(:user_id, User.all, :id, :full_name, {}, {class: "form-control"}) %>
      <% if @photo.errors[:user_id].present? %>
        <div class="error">
          <%= @photo.errors[:user_id].to_sentence %>
        </div>
      <% end %>
    </div>
    <% if @photo.new_record? %>
      <%= f.submit :class => "btn btn-primary"%><%= link_to "Cancel", user_photos_path, :class => "btn btn-danger" %>
    <% else %>
      <%= f.submit :class => "btn btn-primary"%><%= link_to "Cancel", user_photo_path, :class => "btn btn-danger" %>
    <% end %>
  <% end %>
</div>

app/views/photos/edit.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to "All Photos", user_photos_path %></li>
    <li class="breadcrumb-item"><%= link_to @photo.name, [@user, @photo] %></li>
    <li class="breadcrumb-item active" aria-current="page">Edit</li>
  </ol>
</nav>
<h1 class="text-center">Edit <%= @photo.name%></h1>
<hr>
<%= render partial: "form" %>

app/views/photos/index.html.erb
<h1>Photos List of <%= link_to @user.full_name, user_path(@user) %>- <span><%= link_to "Add new Photo", new_user_photo_path %></span> </h1>
<div class="row justify-content-start">
  <% @photos.each do |p| %>
    <div class="col-md-4">
      <div class="card bg-light">
        <div class="card-header"><%= link_to p.name, [@user, p] %></div>
        <div class="card-body">
          <p class="card-text"><i class="fa fa-file"></i> <%= p.file %></p>
          <p class="card-text"><i class="fa fa-user"></i> <%= p.user.full_name %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/photos/new.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to "All Photos", user_photos_path %></li>
    <li class="breadcrumb-item active" aria-current="page">New</li>
  </ol>
</nav>
<h1 class="text-center">Add new photo</h1>
<hr>
<%= render partial: "form" %>

app/views/photos/show.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to "All Photos", user_photos_path %></li>
    <li class="breadcrumb-item active" aria-current="page"><%@photo.name %></li>
  </ol>
</nav>
<h1 class="text-center"><%= @photo.name%></h1>
<hr>
<div class="row justify-content-center">
  <div class="col-md-5 text-center">
    <span><i class="fa fa-file"></i><%= @photo.file %></span><br/>
    <img src="<%= @photo.file %>"/><br/>
    <%= link_to @user.full_name, user_path(@photo.user_id) %><br />
    <span class="btn btn-warning"><%= link_to (fa_icon "edit", text: "Edit Photo"), [:edit, @user, @photo] %></span>
    <span class="btn btn-danger"><%= link_to (fa_icon "trash", text: "Remove Photo"), [@user, @photo], method: :delete, data: {confirm: "Are you sure ?"} %></span>
  </div>
</div>

app/views/users/_form.html.erb
<div class="row justify-content-center" >
  <%=  form_for @user do |f| %>
    <div class="form-group">
      <%= f.label :first_name %>
      <%= f.text_field :first_name, :class => "form-control" %>
      <% if @user.errors[:first_name].present? %>
        <div class="error">
          <%= @user.errors[:first_name].to_sentence %>
        </div>
      <% end %>
    </div>
    <div class="form-group">
      <%= f.label :last_name %>
      <%= f.text_field :last_name, :class => "form-control"%>
      <% if @user.errors[:last_name].present? %>
        <div class="error">
          <%= @user.errors[:last_name].to_sentence %>
        </div>
      <% end %>
    </div>
    <div class="form-group">
      <%= f.label :date_of_birth %>
      <%= f.date_field :date_of_birth, :class => "form-control" %>
      <% if @user.errors[:date_of_birth].present? %>
        <div class="error">
          <%= @user.errors[:date_of_birth].to_sentence %>
        </div>
      <% end %>
    </div>
    <div class="form-group">
      <%= f.label :phone_number %>
      <%= f.text_field :phone_number, :class => "form-control" %>
      <% if @user.errors[:phone_number].present? %>
        <div class="error">
          <%= @user.errors[:phone_number].to_sentence %>
        </div>
      <% end %>
    </div>
    <div class="form-group">
      <%= f.label :email %>
      <%= f.email_field :email, :class => "form-control" %>
      <% if @user.errors[:email].present? %>
        <div class="error">
          <%= @user.errors[:email].to_sentence %>
        </div>
      <% end %>
    </div>
    <% if @user.new_record? %>
      <%= f.submit :class => "btn btn-primary"%><%= link_to "Cancel", users_path, :class => "btn btn-danger" %>
    <% else %>
      <%= f.submit :class => "btn btn-primary"%><%= link_to "Cancel", user_path, :class => "btn btn-danger" %>
    <% end %>
  <% end %>
</div>

app/views/users/edit.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to "All Users", users_path %></li>
    <li class="breadcrumb-item"><%= link_to @user.full_name, user_path %></li>
    <li class="breadcrumb-item active" aria-current="page">Edit</li>
  </ol>
</nav>
<h1 class="text-center">Edit <%= @user.full_name%></h1>
<hr>
<%= render partial: "form" %>

app/views/users/index.html.erb
<h1>Users List- <span><%= link_to "Add new User", new_user_path %></span> </h1>
<div class="row justify-content-start">
  <% @users.each do |u| %>
    <div class="col-md-4">
      <div class="card bg-light">
        <div class="card-header"><%= link_to u.full_name, u %></div>
        <div class="card-body">
          <p class="card-text"><i class="fa fa-birthday-cake"></i> <%= u.date_of_birth %></p>
          <p class="card-text"><i class="fa fa-phone"></i> <%= u.phone_number %></p>
          <p class="card-text"><i class="fa fa-at"></i> <%= u.email %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/new.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to "All Users", users_path %></li>
    <li class="breadcrumb-item active" aria-current="page">New</li>
  </ol>
</nav>
<h1 class="text-center">Add new user</h1>
<hr>
<%= render partial: "form" %>

app/views/users/show.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to "All Users", users_path %></li>
    <li class="breadcrumb-item active" aria-current="page"><%=@user.full_name %></li>
  </ol>
</nav>
<h1 class="text-center"><%= @user.full_name%></h1>
<hr>
<div class="row justify-content-center">
  <div class="col-md-5 text-center">
    <span><i class="fa fa-birthday-cake"></i> <%= @user.date_of_birth %></span><br/>
    <span><i class="fa fa-phone"></i> <%= @user.phone_number %></span><br/>
    <span><i class="fa fa-at"></i> <%= @user.email %></span><br />
    <span class="btn btn-warning"><%= link_to (fa_icon "edit", text: "Edit User"), [ :edit, @user ] %></span>
    <span class="btn btn-danger"><%= link_to (fa_icon "trash", text: "Remove User"), user_path(@user), method: :delete, data: {confirm: "Are you sure ?"} %></span>
  </div>
</div>

<h2 class="text-center"><%= link_to "Photos", user_photos_path(@user) %></h2>
<hr>
<div class="row justify-content-center">
  <% @user.photos.each do |p| %>
    <div class="col-md-2">
      <img src="<%= p.file %>" alt=""/>
      <i><%= link_to p.name, [@user, p] %></i>
    </div>
  <% end %>
</div>